version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frappe
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis:alpine
    restart: always


  backend:
    image: frappe/bench:latest
    working_dir: /workspace/library-bench
    volumes:
      - ./backend/library-bench:/workspace/library-bench
    command: bench start
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
